version: 2
  updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
      interval: "daily"
      versioning-strategy: lockfile-only
      commit-message:
        prefix: "npm"
        include: "scope"
